name: Release Charts

on:
  push:
    branches:
      - main
jobs:
  sync_image:
    name: sync image
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install deps - socat
        run: |
          sudo apt-get update
          sudo apt-get install socat conntrack ebtables ipset -y
          
      - name: Install kube key
        run: |
          sudo curl -sfL https://get-kk.kubesphere.io | VERSION=v2.2.2 sh -
          sudo chmod +x kk
          sudo ./kk version

      - name: Install k8s
        run: |
          sudo ./kk create cluster --with-kubernetes v1.22.10 -y

      - name: Interact with the cluster
        run: |
          mkdir -p $HOME/.kube
          sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
          sudo chown $(id -u):$(id -g) $HOME/.kube/config
          kubectl get nodes
          kubectl get sc

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io" 
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GHCR_PUSH_TOKEN }}" 

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: "deepflowce"
          password: "${{ secrets.REGISTRY_PASS }}"

      - name: Log in to ALIYUN Docker Registry
        uses: docker/login-action@v2
        with:
          registry: "registry.cn-beijing.aliyuncs.com"
          username: "${{ secrets.REGISTRY_ALIYUN_USER }}"
          password: "${{ secrets.REGISTRY_PASS }}"

      - name: add deepflow helm repo
        run: |
          helm repo add deepflow https://deepflowys.github.io/deepflow-charts/
          helm repo update deepflow 

      - name: install deepflow 
        run: |
          helm upgrade --install deepflow -n deepflow deepflow/deepflow --create-namespace \
              -f test-values.yaml

      - name: install skopeo
        run: |
          sudo apt-get update
          sudo apt-get -y install skopeo

      - name: sync image
        run: |
          DEPENDSIMAGE=$(kubectl get pods -n deepflow -o  jsonpath={.items[*].spec.containers[*].image}|awk -F" " '{for(i=1;i<=NF;i++) print $i}' |grep -v deepflow|sort -u)
          for SYNCIMAGE in $DEPENDSIMAGE
            do 
              SORTIMAGE=$(echo $SYNCIMAGE|awk -F/ '{print $NF}')
              echo $SORTIMAGE
              echo "skopeo copy -a  docker://$SYNCIMAGE docker://deepflowce/$SORTIMAGE"
              echo "skopeo copy -a  docker://$SYNCIMAGE docker://registry.cn-beijing.aliyuncs.com/deepflow-ce/$SORTIMAGE"
              echo "skopeo copy -a  docker://$SYNCIMAGE docker://ghcr.io/deepflowys/deepflow-ce/$SORTIMAGE "
              skopeo copy -a  docker://$SYNCIMAGE docker://deepflowce/$SORTIMAGE
              skopeo copy -a  docker://$SYNCIMAGE docker://registry.cn-beijing.aliyuncs.com/deepflow-ce/$SORTIMAGE
              skopeo copy -a  docker://$SYNCIMAGE docker://ghcr.io/deepflowys/deepflow-ce/$SORTIMAGE 
            done

