name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ref:
        description: "Why trigger?"
        required: true 
        type: string
jobs:
  sync_image:
    name: test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Auto install sealos
        uses: labring/sealos-action@v0.0.2
        with:
          sealosVersion: 4.1.3
          buildah: false
          debug: true
          sealctl: true

      - name: Sealos version
        uses: labring/sealos-action@v0.0.2
        with:
          type: version

      - name: Auto install k8s using sealos
        uses: labring/sealos-action@v0.0.2
        with:
          image: labring/kubernetes:v1.24.0
          debug: true
          type: run-k8s
    
      - name: Interact with the cluster
        run: |
          mkdir -p $HOME/.kube
          sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
          sudo chown $(id -u):$(id -g) $HOME/.kube/config
          kubectl get nodes
          kubectl get sc